CREATE DATABASE IF NOT EXISTS Pierre_Sofip DEFAULT CHARACTER SET = 'utf8mb4';

USE Pierre_Sofip;

/* 
• Nom
• Prénom
• Age
• Date de naissance
• Email
• Ville */
CREATE TABLE IF NOT EXISTS Stagiaire (
    StudentID int NOT NULL PRIMARY KEY AUTO_INCREMENT,
    LastName varchar(255) NOT NULL,
    FirstName varchar(255) NOT NULL,
    Birthday DATE NOT NULL,
    Age INT(3) NOT NULL,
    Email varchar(255) NOT NULL,
    City varchar(255) NOT NULL
);

/* populate table */
INSERT INTO
    `Stagiaire` (
        `StudentID`,
        `LastName`,
        `FirstName`,
        `Birthday`,
        `Age`,
        `Email`,
        `City`
    )
VALUES (
        NULL,
        'Dupont',
        'Alice',
        '2007-01-15',
        18,
        'alice.dupont@example.com',
        'Lille'
    ),
    (
        NULL,
        'Garcia',
        'Julie',
        '1996-03-17',
        29,
        'julie.garcia@example.com',
        'Lille'
    ),
    (
        NULL,
        'Leroy',
        'Francois',
        '2002-04-05',
        23,
        'francois.leroy@example.com',
        'Toulouse'
    ),
    (
        NULL,
        'Blanc',
        'Sophie',
        '1987-06-09',
        38,
        'sophie.blanc@example.com',
        'Rennes'
    ),
    (
        NULL,
        'Moreau',
        'Clara',
        '2001-09-19',
        23,
        'clara.moreau@example.com',
        'Nice'
    ),
    (
        NULL,
        'Michel',
        'Ines',
        '1997-08-25',
        28,
        'ines.michel@example.com',
        'Montpellier'
    ),
    (
        NULL,
        'Durand',
        'Emma',
        '2003-11-10',
        21,
        'emma.durand@example.com',
        'Bordeaux'
    ),
    (
        NULL,
        'Simon',
        'Gabriel',
        '2000-06-14',
        25,
        'gabriel.simon@example.com',
        'Strasbourg'
    ),
    (
        NULL,
        'Bertrand',
        'Lea',
        '1994-07-07',
        31,
        'lea.bertrand@example.com',
        'Lyon'
    ),
    (
        NULL,
        'Lefevre',
        'Alexandre',
        '1998-01-08',
        27,
        'alexandre.lefevre@example.com',
        'Rennes'
    ),
    (
        NULL,
        'Thomas',
        'Nina',
        '1992-05-12',
        33,
        'nina.thomas@example.com',
        'Bordeaux'
    ),
    (
        NULL,
        'Robert',
        'Oscar',
        '1991-12-24',
        33,
        'oscar.robert@example.com',
        'Toulouse'
    ),
    (
        NULL,
        'Martin',
        'Benoit',
        '2006-03-22',
        19,
        'benoit.martin@example.com',
        'Paris'
    ),
    (
        NULL,
        'Bernard',
        'Chloe',
        '2005-07-01',
        20,
        'chloe.bernard@example.com',
        'Lyon'
    ),
    (
        NULL,
        'David',
        'Kevin',
        '1995-05-30',
        30,
        'kevin.david@example.com',
        'Paris'
    ),
    (
        NULL,
        'Roux',
        'Mathieu',
        '1993-10-02',
        32,
        'mathieu.roux@example.com',
        'Marseille'
    ),
    (
        NULL,
        'Richard',
        'Pauline',
        '1990-08-01',
        35,
        'pauline.richard@example.com',
        'Nice'
    ),
    (
        NULL,
        'Dubois',
        'Quentin',
        '1989-04-18',
        36,
        'quentin.dubois@example.com',
        'Strasbourg'
    ),
    (
        NULL,
        'Bonnet',
        'Romane',
        '1988-09-29',
        36,
        'romane.bonnet@example.com',
        'Nantes'
    ),
    (
        NULL,
        'Girard',
        'Tom',
        '1986-11-03',
        38,
        'tom.girard@example.com',
        'Montpellier'
    ),
    (
        NULL,
        'Dupont',
        'Ulysse',
        '1985-03-07',
        40,
        'ulysse.dupont@example.com',
        'Lille'
    ),
    (
        NULL,
        'Martin',
        'Victoire',
        '1984-02-14',
        41,
        'victoire.martin@example.com',
        'Paris'
    ),
    (
        NULL,
        'Bernard',
        'William',
        '1983-09-01',
        41,
        'william.bernard@example.com',
        'Lyon'
    ),
    (
        NULL,
        'Petit',
        'David',
        '2004-02-28',
        21,
        'david.petit@example.com',
        'Marseille'
    ),
    (
        NULL,
        'Laurent',
        'Helene',
        '1999-02-03',
        26,
        'helene.laurent@example.com',
        'Nantes'
    ),
    (
        NULL,
        'Petit',
        'Xavier',
        '1982-04-20',
        43,
        'xavier.petit@example.com',
        'Marseille'
    ),
    (
        NULL,
        'Durand',
        'Yara',
        '1981-11-28',
        43,
        'yara.durand@example.com',
        'Bordeaux'
    ),
    (
        NULL,
        'Leroy',
        'Zoe',
        '1980-06-05',
        45,
        'zoe.leroy@example.com',
        'Toulouse'
    ),
    (
        NULL,
        'Moreau',
        'Antoine',
        '1979-01-29',
        46,
        'antoine.moreau@example.com',
        'Nice'
    ),
    (
        NULL,
        'Simon',
        'Laura',
        '1975-07-22',
        50,
        'laura.simon@example.com',
        'Strasbourg'
    );